services:
  redis:
    image: redis:alpine3.20
    container_name: redis_bullmq
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  redis:
    driver: local